// Smart Automation Rules
// Automate reordering, alerts, and stock adjustments

import { supabase } from './supabase';

export interface AutoRule {
  id: string;
  name: string;
  condition: 'low_stock' | 'overstock' | 'expiry_soon' | 'no_movement' | 'slow_moving';
  trigger: {
    thresholdDays?: number;
    minStockLevel?: number;
    maxStockLevel?: number;
    noSalesDays?: number;
  };
  action: 'auto_purchase' | 'alert' | 'discount' | 'block_orders' | 'auto_transfer';
  actionParams?: {
    supplierPreference?: string[];
    discountPercent?: number;
    transferToWarehouse?: string;
  };
  isActive: boolean;
}

// Create automation rule
export async function createAutoRule(
  name: string,
  condition: AutoRule['condition'],
  trigger: AutoRule['trigger'],
  action: AutoRule['action'],
  actionParams?: AutoRule['actionParams'],
): Promise<AutoRule> {
  const { data } = await supabase
    .from('automation_rules')
    .insert({ name, condition, trigger, action, action_params: actionParams, is_active: true })
    .select('*')
    .single();

  return data;
}

// Execute automation rules (run via cron job)
export async function executeAutomationRules(): Promise<void> {
  const { data: rules } = await supabase.from('automation_rules').select('*').eq('is_active', true);

  if (!rules) return;

  for (const rule of rules) {
    switch (rule.condition) {
      case 'low_stock':
        await handleLowStockRule(rule);
        break;
      case 'overstock':
        await handleOverstockRule(rule);
        break;
      case 'expiry_soon':
        await handleExpirySoonRule(rule);
        break;
      case 'no_movement':
        await handleNoMovementRule(rule);
        break;
      case 'slow_moving':
        await handleSlowMovingRule(rule);
        break;
    }
  }
}

async function handleLowStockRule(rule: AutoRule): Promise<void> {
  const { data: products } = await supabase
    .from('products')
    .select('*')
    .lte('current_stock', rule.trigger.minStockLevel || 0);

  if (!products) return;

  for (const product of products) {
    if (rule.action === 'auto_purchase') {
      // Create purchase order automatically
      const supplierPrefs = rule.actionParams?.supplierPreference || [product.supplier_id];
      const supplier = supplierPrefs[0];

      await supabase.from('purchases').insert({
        invoice_number: `AUTO-${Date.now()}`,
        supplier_id: supplier,
        purchase_date: new Date().toISOString().split('T')[0],
        total_amount: 0,
        amount_paid: 0,
        payment_method: 'pending',
        notes: `Auto-generated by rule: ${rule.name}`,
      });

      await supabase.from('alerts').insert({
        type: 'auto_purchase',
        message: `Auto-purchase order created for ${product.name}`,
        product_id: product.id,
        severity: 'info',
      });
    } else if (rule.action === 'alert') {
      await supabase.from('alerts').insert({
        type: 'low_stock',
        message: `Low stock alert: ${product.name} (${product.current_stock} ${product.unit})`,
        product_id: product.id,
        severity: 'high',
      });
    }
  }
}

async function handleOverstockRule(rule: AutoRule): Promise<void> {
  const { data: products } = await supabase
    .from('products')
    .select('*')
    .gte('current_stock', rule.trigger.maxStockLevel || 999999);

  if (!products) return;

  for (const product of products) {
    if (rule.action === 'discount') {
      // Apply discount to move stock
      const discountPercent = rule.actionParams?.discountPercent || 10;
      const newPrice = product.selling_price * (1 - discountPercent / 100);

      await supabase.from('products').update({ selling_price: newPrice }).eq('id', product.id);

      await supabase.from('alerts').insert({
        type: 'overstock',
        message: `Discount applied to ${product.name}: ${discountPercent}% off`,
        product_id: product.id,
        severity: 'warning',
      });
    }
  }
}

async function handleExpirySoonRule(rule: AutoRule): Promise<void> {
  const { data: batches } = await supabase
    .from('batches')
    .select('*')
    .eq('status', 'active')
    .lte(
      'expiry_date',
      new Date(Date.now() + (rule.trigger.thresholdDays || 30) * 24 * 60 * 60 * 1000)
        .toISOString()
        .split('T')[0],
    );

  if (!batches) return;

  for (const batch of batches) {
    await supabase.from('alerts').insert({
      type: 'expiry_soon',
      message: `Product expiring soon: Batch ${batch.batch_number} expires ${batch.expiry_date}`,
      severity: 'critical',
    });
  }
}

async function handleNoMovementRule(rule: AutoRule): Promise<void> {
  const noSalesDays = rule.trigger.noSalesDays || 90;
  const cutoffDate = new Date(Date.now() - noSalesDays * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

  const { data: slowProducts } = await supabase.rpc('get_inactive_products', {
    p_days: noSalesDays,
  });

  if (!slowProducts) return;

  for (const product of slowProducts) {
    if (rule.action === 'alert') {
      await supabase.from('alerts').insert({
        type: 'no_sales',
        message: `No sales for ${noSalesDays} days: ${product.name}`,
        product_id: product.id,
        severity: 'medium',
      });
    }
  }
}

async function handleSlowMovingRule(rule: AutoRule): Promise<void> {
  // Products with very low turnover rate
  const { data: slowMoving } = await supabase.rpc('get_slow_moving_products', {
    p_threshold: 10, // < 10 units per month
  });

  if (!slowMoving) return;

  for (const product of slowMoving) {
    await supabase.from('alerts').insert({
      type: 'slow_moving',
      message: `Slow-moving product detected: ${product.name} (${product.monthly_sales} units/month)`,
      product_id: product.id,
      severity: 'low',
    });
  }
}
